### ISSUE TITLE
List of templates doesn't show

### ISSUE THREAD

**Issue by arsari** [Arcath/file-templates#12]
I install the package and when trigger New File it doesn't list the templates on the directory.  Path for templates was set correctly in the settings.

**Comment by Arcath** [comment]
Have you created any templates through the plugin?

**Comment by arsari** [comment]
hi. no. but I have three templates on the directory pointed.

**Comment by Arcath** [comment]
file-templates uses hashes and an indexing system, any templates you want to use need to be created through the plugin.

**Comment by arsari** [comment]
oh...
Understood.  Thanks for the clarification.
