### ISSUE TITLE
Can't create new template - Cannot read property 'getText' of undefined.

### ISSUE THREAD

**Issue by MartinHKarlsson** [Arcath/file-templates#4]
When I try to create a new template, which I named "html5", I receive the following error message:
Uncaught TypeError: Cannot read property 'getText' of undefined.

Unfortunately I can't create an issue or see the stack trace in Atom as the modal dialog "New Template" is still open. The error seems to occur in:

.atom\packages\file-templates\lib\views\new-template-view.coffee:34

I'm using version 0.1.1 of the file-templates package in Atom 1.0.2 on a PC running Windows 7.

**Comment by Arcath** [comment]
Do you have an active editor open?

**Comment by MartinHKarlsson** [comment]
Yes

**Comment by MartinHKarlsson** [comment]
![image](https://cloud.githubusercontent.com/assets/13315077/8650710/deb0faf0-2974-11e5-81d7-57a3f2c4d9ec.png)

**Comment by Arcath** [comment]
Ah, sorry by active editor I meant a file open.

file-templates takes the contents of your current editor (buffer) and saves it to a folder in your atom settings.

If you want to create a template from an empty file create a new file `Ctrl+N` and put in your code then create a new template from that editor.

**Comment by MartinHKarlsson** [comment]
Ahh, I see. I totally miss understood this feature. I thought it would create a new empty template that I would be able to edit and save. It worked like a charm now when I had a file open. I guess this proves that I didn’t read the documentation very carefully :)
